version: '3.7'
services:
  web:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend/url-shortener
    volumes:
      - ./frontend/url-shortener:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: ["npm", "start"]
volumes:
  postgres_data: