"""Initial migration

Revision ID: f08af139cc6d
Revises: 
Create Date: 2023-07-15 15:18:21.946395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08af139cc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('alias', sa.String(length=5), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_index(op.f('ix_urls_alias'), 'urls', ['alias'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_alias'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
